#!/usr/bin/env bash

R="\e[1;31m"; G="\e[1;32m"; W="\e[1;37m"

kern() { echo -n -e "${G} * ${W}Booting with ${R}$(uname -r) ${W}"; }
dots() { echo -n -e "${W}$@" && read -rt ".25" <> <(:) || :; }

{
    kern
    dots ""; dots "."; dots "."; dots "."
    echo -e "\ec"
}

/sbin/openrc sysinit
