#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# Firmware Setup
menuentry 'Firmware Setup' --class efi {
    fwsetup
}
# Reboot & Poweroff
menuentry 'Reboot System' --class restart {
    reboot
}
menuentry 'Poweroff System' --class shutdown {
    halt
}
